# Logo
logo_image_source: https://f.easyuploader.app/eu-prd/upload/20200823141906_6e3067793936347a667a.png

# Index Page
index_banner_text: SkyleafBlog
index_banner_text_secondary: スカイリーフ株式会社有志によるブログです。
index_font_awesome_icon_css: fa fa-leaf

# Header
menu:
  Home: /
  Archives: /archives
#  Tags: /tags
#  Categories: /categories
#  About: /about.html
#  Contact: /contact.html

# Post
default_post_title: Untitled
default_post_icon: fa fa-leaf

# Archive Date Format
archive_date_format: MMM YYYY
archive_font_awesome_icon_css: fa-leaf

# About Widget
# about_widget_avatar_url: https://f.easyuploader.app/eu-prd/upload/20200823142003_68614e5a366a59724561.jpg
# about_widget_avatar_url: https://f.easyuploader.app/eu-prd/upload/20200823141906_6e3067793936347a667a.png
about_widget_avatar_url: https://f.easyuploader.app/eu-prd/upload/20210115233150_6b7462435276386259684f4434536e4d.png

about_widget_text: ""


# Comments.
comments:
  # Disqus comments
  disqus_shortname: 

# Google Analytics Tracking ID
google_analytics: UA-186358407-1

# Social Media Platforms
social_platforms:
#  - url: https://twitter.com/?lang=en
#    fa_icon: fa-twitter
#  - url: https://www.facebook.com/
#    fa_icon: fa-facebook
#  - url: https://dribbble.com/
#    fa_icon: fa-dribbble 
  - url: https://github.com/skyleaf0511
    fa_icon: fa-github
  - url: https://skyleaf.co.jp/
    fa_icon: fa-leaf
#  - url: https://plus.google.com/
#    fa_icon: fa-google-plus
#  - url: https://www.behance.net/
#    fa_icon: fa-behance
#  - url: https://500px.com/
#    fa_icon: fa-500px
#  - url: mailto:test@example.com
#    fa_icon: fa-envelope
#  - url: /#
#    fa_icon: fa-rss

# Footer about
footer_about: "@Skyleaf. All right reserved | Design & Hexo <a class=\"link dim white\" href=\"http://www.codeblocq.com/\">Jonathan Klughertz</a>"
